[package]
name = "skunk-api-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.60"
