[workspace]
resolver = "2"
members = [
  "skunk",
  "skunk-bytes",
  "skunk-cli",
  "skunk-macros",
]

[patch.crates-io]
hyper = { git = "https://github.com/jgraef/hyper.git", branch = "switch/main" }
