[workspace]
resolver = "2"
members = [
  "byst",
  "byst-macros",
  "skunk",
  "skunk-api",
  "skunk-cli",
  "skunk-macros",
  "skunk-ui",
]

[patch.crates-io]
reqwest-websocket = { git = "https://github.com/jgraef/reqwest-websocket.git" }
