[package]
name = "skunk"
version = "0.1.0"
edition = "2021"
description = "A person-in-the-middle proxy"
readme = "README.md"
homepage = "https://github.com/jgraef/skunk"
repository = "https://github.com/jgraef/skunk"
license = "MIT"
keywords = ["mitm", "proxy"]
categories = [
    "network-programming",
]

[dependencies]
async-trait = { version = "0.1.80", optional = true }
futures-util = "0.3.30"
hyper = { version = "1.3.1", features = ["http1", "server", "client"], optional = true }
hyper-util = { version = "0.1.3", features = ["tokio"], optional = true }
indexmap = "2.2.6"
nom = "7.1.3"
pin-project-lite = "0.2.14"
rcgen = { version = "0.13.1", default-features = false, features = ["aws_lc_rs", "pem", "x509-parser"], optional = true }
regex = "1.10.4"
rustls = { version = "0.23.5", optional = true }
rustls-native-certs = "0.7.0"
rustls-pemfile = { version = "2.1.2", optional = true }
socks5-server = { version = "0.10.1", optional = true }
sqlx = { version = "0.7.4", features = ["runtime-tokio", "sqlite"], optional = true }
thiserror = "1.0.60"
tokio = { version = "1.37.0", features = ["macros", "net", "io-util"] }
tokio-rustls = { version = "0.26.0", optional = true }
tokio-util = "0.7.11"
tracing = "0.1.40"
tracing-unwrap = { version = "1.0.1", features = ["log-location"] }

[features]
default = ["full"]
full = ["store", "socks", "tls", "http", "store"]
socks = ["dep:socks5-server", "dep:async-trait"]
tls = ["dep:rcgen", "dep:rustls", "dep:rustls-pemfile", "dep:tokio-rustls"]
http = ["dep:hyper", "dep:hyper-util"]
store = ["dep:sqlx"]
