[package]
name = "byst"
version = "0.1.0"
edition = "2021"

[features]
default = []
bytes-impl = []

[dependencies.byst-macros]
#version = "0.1.0"
path = "../byst-macros"

[dependencies]
thiserror = "1.0.60"
derive_more = "0.99.17"
