[package]
name = "skunk-cli"
version = "0.1.0"
edition = "2021"
description = "A person-in-the-middle proxy"
readme = "README.md"
homepage = "https://github.com/jgraef/skunk"
repository = "https://github.com/jgraef/skunk"
license = "MIT"
keywords = ["mitm", "proxy"]
categories = [
    "command-line-utilities",
]

[[bin]]
name = "skunk"
path = "src/main.rs"

[dependencies.skunk-api]
path = "../skunk-api"
features = ["server"]

[dependencies.byst]
#version = "0.1.0"
path = "../byst"

[dependencies]
axum = "0.7.5"
clap = { version = "4.5.8", features = ["derive", "env"] }
color-eyre = "0.6.3"
dirs = "5.0.1"
dotenvy = "0.15.7"
futures = "0.3.30"
reverse-proxy-service = { git = "https://github.com/jgraef/reverse-proxy-service.git", branch = "switch/update", features = ["axum"] }
serde = { version = "1.0.201", features = ["derive"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "signal"] }
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dependencies.skunk]
#version = "0.1.0"
path = "../skunk"
features = ["full"]
