[package]
name = "confix"
version = "0.1.0"
edition = "2021"

[dependencies.notify-async]
path = "../notify-async"

[dependencies]
thiserror = "1.0.62"
murmur3 = "0.5.2"
tokio = { version = "1.38.0", default-features = false, features = ["sync"] }
winnow = "0.6.13"
