name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        toolchain: [ nightly ]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt

      - name: Set up Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Cargo:fmt
        run: cargo fmt --all -- --check

      - name: Run Cargo:test
        run: cargo test --verbose --all-features
